LANGUAGE_DICTIONARY = {
    "Prettier Config": ['.prettierrc'],
    "1C Enterprise": ['.bsl', '.os'],
    "ABAP": ['.abap'],
    "ABAP Objects": ['.abap'],
    "ABNF": ['.abnf'],
    "Action": ['.act'],
    "ActionScript": ['.as'],
    "Ada": ['.adb', '.ads'],
    "Ada 95": ['.adb', '.ads'],
    "AGSScript": ['.asc'],
    "Agda": ['.agda'],
    "AMPL": ['.mod'],
    "Angular": ['.component.ts', '.service.ts', '.pipe.ts', '.module.ts', '.guard.ts', '.directive.ts'],
    "APL": ['.apl'],
    "ASP.NET": ['.aspx', '.ascx'],
    "Assembly": ['.asm'],
    "Astro": ['.astro'],
    "ATS": ['.dats', '.sats', '.hats'],
    "AutoHotkey": ['.ahk'],
    "AutoIt": ['.au3'],
    "Awk": ['.awk'],
    "Ballerina": ['.bal'],
    "Bash": ['.sh'],
    "Batch": ['.bat', '.cmd'],
    "Befunge": ['.befunge'],
    "BitBake": ['.bb', '.bbappend', '.bbclass'],
    "BlitzMax": ['.bmx'],
    "Bluespec": ['.bsv'],
    "Boo": ['.boo'],
    "Bosque": ['.bsq'],
    "Brainfuck": ['.b', '.bf'],
    "C": ['.c', '.h'],
    "C++": ['.cpp', '.cxx', '.cc', '.h', '.hpp'],
    "Carbon": ['.carbon', '.cpp2'],
    "CartoCSS": ['.mss'],
    "Ceylon": ['.ceylon'],
    "Chapel": ['.chpl'],
    "Cirru": ['.cirru'],
    "Clarion": ['.clw'],
    "Clarity": ['.clar'],
    "Clean": ['.icl', '.dcl'],
    "Clipper": ['.prg'],
    "Clojure": ['.clj', '.cljs', '.cljc'],
    "ClojureScript": ['.cljs'],
    "CMake": ['CMakeLists.txt'],
    "COBOL": ['.cob', '.cbl'],
    "CoffeeScript": ['.coffee'],
    "ColdFusion": ['.cfm', '.cfc'],
    "Cool": ['.cool'],
    "Coq": ['.v'],
    "Crystal": ['.cr'],
    "CSS": ['.css'],
    "Custom Model File": ['ModelFile'],
    "Cypress": ['.cy.js', '.cy.jsx', '.cy.ts', '.cy.tsx'],
    "Cython": ['.pyx'],
    "D": ['.d'],
    "Dart": ['.dart'],
    "Darwin": ['.dwn'],
    "Dockerfile": ['Dockerfile'],
    "DTrace": ['.d'],
    "Dylan": ['.dylan'],
    "E": ['.e'],
    "Eiffel": ['.e'],
    "Elixir": ['.ex', '.exs'],
    "Elm": ['.elm'],
    "Environment": ['.env'],
    "Erlang": ['.erl', '.hrl'],
    "Euphoria": ['.e'],
    "F#": ['.fs', '.fsi'],
    "Factor": ['.factor'],
    "Fantom": ['.fan'],
    "Forth": ['.fs', '.fth'],
    "Fortran": ['.f', '.for', '.f90'],
    "FoxPro": ['.prg'],
    "GAP": ['.g'],
    "GAMS": ['.gms'],
    "Genie": ['.gs'],
    "Gherkin": ['.feature'],
    "Git Configuration": ['.gitignore'],
    "GML": ['.gml'],
    "Go": ['.go'],
    "Gosu": ['.gs', '.gsx'],
    "GraphQL": ['.graphql', '.gql'],
    "Groff": ['.groff'],
    "Groovy": ['.groovy', '.gvy'],
    "Hack": ['.hh'],
    "Haskell": ['.hs'],
    "Haxe": ['.hx'],
    "Hoon": ['.hoon'],
    "HTML": ['.html', '.htm'],
    "Hy": ['.hy'],
    "IDL": ['.idl'],
    "Ini": ['.ini'],
    "Ink": ['.ink'],
    "Io": ['.io'],
    "J": ['.ijs'],
    "J#": ['.jsl'],
    "Janus": ['.janus'],
    "Java": ['.java'],
    "JavaScript": ['.js', '.mjs'],
    "JavaScript React": ['.jsx'],
    "Jest Tests": ['.test.js', '.test.jsx', '.test.ts', '.test.tsx', '.spec.js', '.spec.jsx', '.spec.ts', '.spec.tsx'],
    "Jinja": ['.jinja', '.jinja2'],
    "Jolie": ['.ol'],
    "JSON": ['.json'],
    "Julia": ['.jl'],
    "kdb+": ['.q'],
    "Kotlin": ['.kt', '.kts'],
    "Kotlin Script": ['.kts'],
    "KRL": ['.krl'],
    "LabVIEW": ['.vi'],
    "LaTeX": ['.tex'],
    "Lean": ['.lean', '.hlean'],
    "Lisp": ['.lisp', '.lsp'],
    "LiveScript": ['.ls'],
    "LoomScript": ['.ls'],
    "Lua": ['.lua'],
    "MATLAB": ['.m'],
    "Max/MSP": ['.maxpat'],
    "Mercury": ['.m', '.int'],
    "MetaPost": ['.mp'],
    "Mirah": ['.druby', '.mirah'],
    "ML": ['.ml'],
    "Modula-2": ['.mod'],
    "MoonScript": ['.moon'],
    "MQL4": ['.mq4'],
    "MQL5": ['.mq5'],
    "Neko": ['.neko'],
    "Next.js": ['.next.js', '.next.ts', '.next.jsx', '.next.tsx', 'next.config.js', 'next.config.ts'],
    "Nial": ['.ndf'],
    "Nim": ['.nim'],
    "NXT-G": ['.rbt'],
    "Objective-C": ['.m', '.mm'],
    "OCaml": ['.ml', '.mli'],
    "OpenCL": ['.cl'],
    "OpenEdge": ['.p', '.w'],
    "OpenEdge ABL": ['.p'],
    "OpenSCAD": ['.scad'],
    "Oz": ['.oz'],
    "Pascal": ['.pas'],
    "Perl": ['.pl', '.pm'],
    "PHP": ['.php', '.phtml'],
    "Pig": ['.pig'],
    "Pike": ['.pike'],
    "PL/I": ['.pli'],
    "PL/SQL": ['.pls', '.plb'],
    "PostScript": ['.ps'],
    "PowerShell": ['.ps1', '.psm1'],
    "Prolog": ['.pl', '.pro'],
    "Propeller Spin": ['.spin'],
    "PureScript": ['.purs'],
    "Python": ['.py'],
    "Q": ['.q'],
    "QML": ['.qml'],
    "R": ['.r', '.R'],
    "Racket": ['.rkt'],
    "Ragel": ['.rl'],
    "Rascal": ['.rsc'],
    "React Native": ['.native.js', '.native.jsx', '.native.ts', '.native.tsx'],
    "Reason": ['.re', '.rei'],
    "Remix": ['.remix.js', '.remix.ts', '.remix.jsx', '.remix.tsx'],
    "REXX": ['.rexx', '.rex'],
    "Ring": ['.ring'],
    "RPG": ['.rpgle', '.rpg'],
    "RPG IV": ['.rpgle'],
    "Ruby": ['.rb'],
    "Rust": ['.rs'],
    "SAS": ['.sas'],
    "Scala": ['.scala'],
    "Scheme": ['.scm'],
    "Scratch": ['.sb3'],
    "Sed": ['.sed'],
    "Self": ['.self'],
    "Shell": ['.sh', '.bash'],
    "Shen": ['.shen'],
    "Slash": ['.slash'],
    "Small Basic": ['.sb'],
    "Smalltalk": ['.st'],
    "Smarty": ['.tpl'],
    "SML": ['.sml', '.sig'],
    "Snowball": ['.sbl'],
    "Solidity": ['.sol'],
    "SPARK": ['.spark'],
    "SQL": ['.sql'],
    "Squirrel": ['.nut'],
    "Storybook": ['.stories.js', '.stories.jsx', '.stories.ts', '.stories.tsx'],
    "Stylus": ['.styl'],
    "Svelte": ['.svelte'],
    "Swift": ['.swift'],
    "SystemVerilog": ['.sv', '.svh'],
    "TADS": ['.t'],
    "Tcl": ['.tcl'],
    "Tcl/Tk": ['.tcl'],
    "TeX": ['.tex'],
    "Thrift": ['.thrift'],
    "TLA+": ['.tla'],
    "TOML": ['.toml'],
    "Turing": ['.t'],
    "TypeScript": ['.ts'],
    "TypeScript React": ['.tsx'],
    "Vala": ['.vala'],
    "Varnish Configuration Language": ['.vcl'],
    "VB.NET": ['.vb', '.vbx'],
    "VB6": ['.vbp', '.frm'],
    "VBScript": ['.vbs'],
    "VBScript Classic": ['.asp'],
    "Verilog": ['.v', '.vh'],
    "VHDL": ['.vhd', '.vhdl'],
    "Visual Basic": ['.vb'],
    "Visual FoxPro": ['.prg'],
    "Vue.js": ['.vue'],
    "Vyper": ['.vy'],
    "Web Components": ['.web.js', '.web.ts'],
    "WebAssembly": ['.wat', '.wasm'],
    "Wikitext": ['.wiki'],
    "Wisp": ['.wisp'],
    "Wolfram": ['.wl', '.wls'],
    "Wolfram Language": ['.wl', '.wls'],
    "Wren": ['.wren'],
    "WSDL": ['.wsdl'],
    "X++": ['.xpp'],
    "X10": ['.x10'],
    "XML": ['.xml'],
    "Xojo": ['.xojo_code', '.xojo_menu'],
    "Xtend": ['.xtend'],
    "YAML": ['.yaml', '.yml'],
    "YANG": ['.yang'],
    "Yocto": ['.bb', '.bbappend'],
    "Yorick": ['.i'],
    "Zeek": ['.zeek', '.bro'],
    "Zig": ['.zig'],
    "ZPL": ['.zpl'],
    "Mojo": ['.mojo', '.🔥'],
    "Gleam": ['.gleam'],
    "Roc": ['.roc'],
    "Vale": ['.vale'],
    "Unison": ['.u']
}
